export const products = [
  {
    id: 1,
    name: "Men's Jacket",
    price: 12000,
    rating: 4,
    featured: true,
    image: "/assets/jacket.jpg",
  },
  {
    id: 2,
    name: "Smartwatch",
    price: 85000,
    rating: 5,
    featured: false,
    image: "/assets/smartwatch.jpg",
  },
  {
    id: 3,
    name: "Women's Sneakers",
    price: 18500,
    rating: 5,
    featured: true,
    image: "/assets/sneakers.jpg",
  },
  {
    id: 4,
    name: "Bluetooth Speaker",
    price: 20000,
    rating: 4,
    featured: false,
    image: "/assets/speaker.jpg",
  },
  {
    id: 5,
    name: "Leather wallet",
    price: 12000,
    rating: 5,
    featured: true,
    image: "/assets/wallet.jpg",
  },
  {
    id: 6,
    name: "Wireless Mouse",
    price: 7000,
    rating: 3,
    featured: false,
    image: "/assets/mouse.jpg",
  },
  {
    id: 7,
    name: "Sunglasses",
    price: 13000,
    rating: 4,
    featured: false,
    image: "/assets/sunglasses.jpg",
  },
  {
    id: 8,
    name: "Sports Wear",
    price: 17000,
    rating: 4,
    featured: true,
    image: "/assets/yellowcloth.jpg",
  },
  {
    id: 9,
    name: "Sports Shoes",
    price: 25000,
    rating: 5,
    featured: false,
    image: "/assets/sheos.jpg",
  },
  {
    id: 10,
    name: "Gentle-men Watch",
    price: 6500,
    rating: 4,
    featured: false,
    image: "/assets/watch.jpg",
  },
  {
    id: 11,
    name: "Desk Lamp",
    price: 20000,
    rating: 5,
    featured: false,
    image: "/assets/desklamp.jpg",
  },
  {
    id: 13,
    name: "Men's Suit",
    price: 50000,
    rating: 5,
    featured: false,
    image: "/assets/huzaifa2.jpg",
  },
  {
    id: 14,
    name: "Women's Suit",
    price: 80500,
    rating: 5,
    featured: false,
    image: "/assets/aiony.jpg",
  },
  {
    id: 15,
    name: "Fitness Tracker",
    price: 10000,
    rating: 5,
    featured: false,
    image: "/assets/fitnesstracker.jpg",
  },
  {
    id: 16,
    name: "Wireless Headphones",
    price: 18000,
    rating: 5,
    featured: false,
    image: "/assets/headphones.jpg",
  },
  {
    id: 17,
    name: "Smart Thermostat",
    price: 17000,
    rating: 5,
    featured: false,
    image: "/assets/smartthermostart.jpg",
  },
  {
    id: 18,
    name: "White lady's Dress",
    price: 107000,
    rating: 5,
    featured: false,
    image: "/assets/dress.jpg",
  },
];